version: "3"
rpc:
  listen: "tcp://127.0.0.1:6001"
server:
  command: "php public/index.php"
  relay: pipes
reload:
  enable: true
  watch: [".php"]
  services:
    http:
      watch: [".php", ".dark.php"]
      dirs: ["src"]
http:
  address: "0.0.0.0:3636"
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 100
kv:
  local:
    driver: memory
    config:
      interval: 60
metrics:
  address: "127.0.0.1:2112"
service:
  hello:
    command: "php src/services/hello.php"
    remain_after_exit: true
  mpd:
    command: "/usr/bin/mpd --stderr --no-daemon /tmp/mpd.conf"
    user: "root"
  centrifugo:
    command: "/app/bin/centrifugo -c /etc/centrifugo/config.json"
    user: "root"
centrifuge:
  # Centrifugo server proxy address (docs: https://centrifugal.dev/docs/server/proxy#grpc-proxy)
  # Optional, default: tcp://127.0.0.1:30000
  proxy_address: "tcp://127.0.0.1:30000"

  # gRPC server API address (docs: https://centrifugal.dev/docs/server/server_api#grpc-api)
  # Optional, default: tcp://127.0.0.1:30000. Centrifugo: `grpc_api` should be set to true and `grpc_port` should be the same as in the RR's config.
  grpc_api_address: "tcp://127.0.0.1:30000"

  # Use gRPC gzip compressor
  # Optional, default: false
  use_compressor: true

  # Your application version
  # Optional, default: v1.0.0
  version: "v1.0.0"

  # Your application name
  # Optional, default: roadrunner
  name: "moopl"

  # TLS configuration
  # Optional, default: null
