---
services:
  franken:
    #image: dunglas/frankenphp
    image: franken-dev
    build:
      context: ./
      dockerfile: docker/Dockerfile.franken
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    env_file:
      - path: .pubkey.env
        # wird erst durch den installer erstellt
        required: false
    environment:
      #- FRANKENPHP_CONFIG=worker /app/public/index.php
      #- MERCURE_PUBLISHER_JWT_KEY=$MERCURE_PUBLISHER_JWT_KEY
      - MERCURE_PUBLISHER_JWT_ALG=$MERCURE_PUBLISHER_JWT_ALG
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./:/app/
      #- ./franken-test:/app/public
      - caddy_data:/data
      - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    #network_mode: host
  mpd:
    image: giof71/mpd-alsa:vanilla-bookworm
    #profiles: ["dev"]
    #devices:
    #  - /dev/snd:/dev/snd
    ports:
      - 6600:6600/tcp # mpd
      - 8700:8000 # http stream
    environment:
      - PULSE_SERVER=host.docker.internal
      - PULSE_AUDIO_OUTPUT_CREATE=yes
      - USER_MODE=Y
    volumes:
      - ./docker/mpd.conf:/user/config/override.mpd.conf
      # - ~/.config/pulse:/home/mpd-user/.config/pulse
      - ./lastfm.txt:/user/config/lastfm.txt:ro
      - ./librefm.txt:/user/config/librefm.txt:ro
      - ~/Music:/music:ro
    restart: unless-stopped
    #entrypoint: ["/usr/bin/rr", "serve", "--dotenv", ".env", "-c", ".rr.docker.yaml"]
    #entrypoint: ["/app/bin/run-mpd.sh"]

  install:
    image: franken-dev
    volumes:
      - ./:/app
    restart: no
    entrypoint: ["make"]
  # events:
  #   image: franken-dev
  #   volumes:
  #     - ./:/app
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   entrypoint: ["php", "src/services/mpd_events.php"]
  #   depends_on:
  #     - franken
  #     - mpd
  #   restart: unless-stopped

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
