#!/bin/bash

docker compose run --rm --entrypoint composer franken update
docker compose run --rm --entrypoint php franken src/migrate.php
docker-compose up
# docker-compose exec franken src/migrate.php
